# Fix mojibake encoding by binary byte replacement
# Turkish characters that were encoded as UTF-8, then each byte read as CP1252, then re-saved as UTF-8

function Replace-ByteSequence {
    param([byte[]]$data, [byte[]]$pattern, [byte[]]$replacement)
    $result = New-Object System.Collections.Generic.List[byte]
    $i = 0
    $pLen = $pattern.Length
    $dLen = $data.Length
    while ($i -lt $dLen) {
        if ($i -le ($dLen - $pLen)) {
            $match = $true
            for ($j = 0; $j -lt $pLen; $j++) {
                if ($data[$i + $j] -ne $pattern[$j]) { $match = $false; break }
            }
            if ($match) {
                $result.AddRange([byte[]]$replacement)
                $i += $pLen
                continue
            }
        }
        $result.Add($data[$i])
        $i++
    }
    return , $result.ToArray()
}

# Replacement table: [mojibake bytes] -> [correct UTF-8 bytes]
# Generated by: for each Turkish char, get UTF-8 bytes, read each byte as CP1252 char, re-encode as UTF-8
$replacements = @(
    # ü (U+00FC): correct=[195,188] moji=[195,131,194,188]
    @{ moji=[byte[]](195,131,194,188); correct=[byte[]](195,188) },
    # ö (U+00F6): correct=[195,182] moji=[195,131,194,182]
    @{ moji=[byte[]](195,131,194,182); correct=[byte[]](195,182) },
    # ç (U+00E7): correct=[195,167] moji=[195,131,194,167]
    @{ moji=[byte[]](195,131,194,167); correct=[byte[]](195,167) },
    # ğ (U+011F): correct=[196,159] moji=[195,132,197,184]
    @{ moji=[byte[]](195,132,197,184); correct=[byte[]](196,159) },
    # ş (U+015F): correct=[197,159] moji=[195,133,197,184]
    @{ moji=[byte[]](195,133,197,184); correct=[byte[]](197,159) },
    # ı (U+0131): correct=[196,177] moji=[195,132,194,177]
    @{ moji=[byte[]](195,132,194,177); correct=[byte[]](196,177) },
    # Ü (U+00DC): correct=[195,156] moji=[195,131,197,147]
    @{ moji=[byte[]](195,131,197,147); correct=[byte[]](195,156) },
    # Ö (U+00D6): correct=[195,150] moji=[195,131,226,128,147]
    @{ moji=[byte[]](195,131,226,128,147); correct=[byte[]](195,150) },
    # Ç (U+00C7): correct=[195,135] moji=[195,131,226,128,161]
    @{ moji=[byte[]](195,131,226,128,161); correct=[byte[]](195,135) },
    # İ (U+0130): correct=[196,176] moji=[195,132,194,176]
    @{ moji=[byte[]](195,132,194,176); correct=[byte[]](196,176) },
    # Ğ (U+011E): correct=[196,158] moji=[195,132,197,190]
    @{ moji=[byte[]](195,132,197,190); correct=[byte[]](196,158) },
    # Ş (U+015E): correct=[197,158] moji=[195,133,197,190]
    @{ moji=[byte[]](195,133,197,190); correct=[byte[]](197,158) },
    # ' (U+2019): correct=[226,128,153] moji=[195,162,226,130,172,226,132,162]
    @{ moji=[byte[]](195,162,226,130,172,226,132,162); correct=[byte[]](226,128,153) },
    # – (U+2013): correct=[226,128,147] moji=[195,162,226,130,172,226,128,156]
    @{ moji=[byte[]](195,162,226,130,172,226,128,156); correct=[byte[]](226,128,147) }
)

$files = @(
    "c:\Users\Yusuf Kahraman\Desktop\Zyro\index.html",
    "c:\Users\Yusuf Kahraman\Desktop\Zyro\app.js"
)

foreach ($file in $files) {
    Write-Host "Processing: $file"
    $data = [System.IO.File]::ReadAllBytes($file)
    
    # Strip BOM if present
    if ($data.Length -ge 3 -and $data[0] -eq 0xEF -and $data[1] -eq 0xBB -and $data[2] -eq 0xBF) {
        $data = $data[3..($data.Length-1)]
        Write-Host "  Stripped BOM"
    }
    
    $originalLen = $data.Length
    foreach ($rep in $replacements) {
        $data = Replace-ByteSequence -data $data -pattern $rep.moji -replacement $rep.correct
    }
    
    Write-Host ("  Length: {0} -> {1} (saved {2} bytes)" -f $originalLen, $data.Length, ($originalLen - $data.Length))
    [System.IO.File]::WriteAllBytes($file, $data)
    Write-Host "  Saved: $file"
}

Write-Host "All done!"
